language: ruby
rvm:
- 2.1
- 2.2
- 2.3.0
before_install:
- gem update bundler
deploy:
  provider: rubygems
  api_key:
    secure: oVkgD3cQ4sO8b0wujOc0vLyYdYbfuMSzvc5a7MPGopIsRqEXL8lgDsPTN61RX6MwvItIrtpEjpAKrNcRFqgs/JCDtKck7ccoyhgvTqJd8JIqdOU+ffZ0v8xYQwjnafduL6hnJiXP1zKZN59K2M20A66xLOvbLzG4Piyep2zkkDzG0+HuH35aA8r9IBqyoOZ8xunXeuDy3AicmPvK+ABQxfgmcA0uOmvkr/ufT+eXluFMvturTvt3dor2HOskyspZdWrzNgMQqjo/0wO3vyq5IIzQINT2cYejut4Oaf3c6QBEVWwOQsSQxJSMru8FuwgvBNwbQ9ojYgqY7i3spMJezNKdz40ZzX42jk9MnLZsc9BO2wT8l6ld1xFRZgKQTrSY2XoCytI9qbuSU+2+y8N2AijjSaPnwKBNG2Ln4ZFoKsgtE+nmZ46keDueh8y+4ZGjtP7NSJ+xgFRhAD8Wx/Dnzskf/+UomSsORLuLry0ilB1MxZdW4pyvuIlqy2MeFH1vsvxyhkLO8MKUYpNd1xJe87SehxzfmGDXYmghPnBFvcFJO3BI33vUygt0nJp9JVGhVzAiXrRMba25oeu9TyEpzow5fdJaITEKap25Qz6fxVcvaOGzS00Ztz31yFNVP85gqcBpigtub6wEl7SC7Vf2MG6O/Ps+Y27Bc74SNfUz7bk=
  gem: sensu-plugins-turbine
  on:
    tags: true
    repo: mickfeech/sensu-plugins-turbine
